### ISSUE TITLE
loreai pi does not work on 0.30.0

### ISSUE THREAD

**Issue by aminvakil** [BYK/opencode-lore#763]
```
 pi: lore compaction unavailable — this session was not routed through Lore; falling back to Pi compaction.                                                                                                                                 
─[lore] local embedding provider failed to init: Cannot find module 'onnxruntime-node'──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Require stack:ify (main) • deployment
- /usr/lib/node_modules/loreai/dist/embedding-worker.cjs. Set search.embeddings.provider in .lore.json to use a remote provider. Error: embedding worker init failed: Cannot find module 'onnxruntime-node'                   gpt-5.5 • high
Require stack:
- /usr/lib/node_modules/loreai/dist/embedding-worker.cjs
    at Worker.<anonymous> (/usr/lib/node_modules/loreai/dist/index.cjs:1926:4166)
    at Worker.emit (node:events:509:20)
```

I'm installing them like this:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=loreai
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=loreai-pi

**Comment by aminvakil** [comment]
It's breaking my workflow with its current state, even without using /compact lots of errors pop up, I'll keep on maintaining the packages on AUR, but I cannot keep on testing them locally anymore.

**Comment by BYK** [comment]
Sorry I missed this over the weekend. On it @aminvakil!
